---
- name: Create pods using deployment 
  hosts: kubernetes 
  become: true
  user: root
 
  tasks: 
  - name: copy deployment file to the k8s server at /home/ec2-user location
    copy: src=./{{ item }} dest=/home/ec2-user
    with_items:
    - deployment.yaml
    - service.yaml
  - name: create a deployment
    command: kubectl apply -f /home/ec2-user/deployment.yaml
 
 # - name: update deployment with new pods if image updated in docker hub
 #   command: kubectl rollout restart deployment.v1.apps/valaxy-deployment
