---
- name: create service for deployment
  hosts: kubernetes
  become: true
  user: root

  tasks:
  - name: copy service.yaml file to /home/ec2-user on k8s server
    copy:
      src: ./service.yaml
      dest: /home/ec2-user
  - name: create a service
    command: kubectl apply -f /home/ec2-user/service.yaml
