apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mohasin-deployment
spec:
  selector:
    matchLabels:
      app: mohasin-devops-project-pod
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: mohasin-devops-project-pod
    spec:
      containers:
      - name: mohasin-devops-project-container
        image: mpmohasin9/hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
