apiVersion: v1
kind: Service
metadata:
  name: mohasin-service
  labels:
    app: mohasin-devops-project-service
spec:
  selector:
    app: mohasin-devops-project-pod
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 31200
